export function getData(){
  return {
    data:[
      {title:'SIM卡总数',num:18,icon:'sim_card',color:'sim_card'},
      {title:'当前在线用户数',num:18,icon:'perm_identity',color:'perm_identity'},
      {title:'在线的SIMPool数量',num:18,icon:'sim_card',color:'sim_card1'},
      {title:'待使用的SIM卡数量',num:18,icon:'sim_card',color:'sim_card2'},
      {title:'禁用的SIM卡数量',num:18,icon:'no_sim',color:'no_sim'},
      {title:'损坏的SIM卡数量',num:18,icon:'signal_cellular_no_sim',color:'signal_cellular_no_sim'},
    ],
    data2:[
        {name:'Afghanistan',value:15},
        {name:'Singapore',value:10000000005},
        {name:'Angola',value:15},
        {name:'Albania',value:15},
        {name:'United Arab Emirates',value:15},
        {name:'Argentina',value:15},
        {name:'Armenia',value:15},
        {name:'French Southern and Antarctic Lands',value:15},
        {name:'Australia',value:15},
        {name:'Austria',value:15},
        {name:'Azerbaijan',value:15},
        {name:'Burundi',value:15},
        {name:'Belgium',value:15},
        {name:'Benin',value:15},
        {name:'Burkina Faso',value:15},
        {name:'Bangladesh',value:15},
        {name:'Bulgaria',value:15},
        {name:'The Bahamas',value:15},
        {name:'Bosnia and Herzegovina',value:15},
        {name:'Belarus',value:15},
        {name:'Belize',value:15},
        {name:'Bermuda',value:15},
        {name:'Bolivia',value:15},
        {name:'Brazil',value:15},
        {name:'Brunei',value:15},
        {name:'Bhutan',value:15},
        {name:'Botswana',value:15},
        {name:'Central African Republic',value:15},
        {name:'Canada',value:15},
        {name:'Switzerland',value:15},
        {name:'Chile',value:15},
        {name:'China',value:15},
        {name:'Ivory Coast',value:15},
        {name:'Cameroon',value:15},
        {name:'Democratic Republic of the Congo',value:15},
        {name:'Republic of the Congo',value:15},
        {name:'Colombia',value:15},
        {name:'Costa Rica',value:15},
        {name:'Cuba',value:15},
        {name:'Northern Cyprus',value:15},
        {name:'Cyprus',value:15},
        {name:'Czech Republic',value:15},
        {name:'Germany',value:15},
        {name:'Djibouti',value:15},
        {name:'Denmark',value:15},
        {name:'Dominican Republic',value:15},
        {name:'Algeria',value:15},
        {name:'Ecuador',value:15},
        {name:'Egypt',value:15},
        {name:'Eritrea',value:15},
        {name:'Spain',value:15},
        {name:'Estonia',value:15},
        {name:'Ethiopia',value:15},
        {name:'Finland',value:15},
        {name:'Fiji',value:15},
        {name:'Falkland Islands',value:15},
        {name:'France',value:15},
        {name:'Gabon',value:15},
        {name:'United Kingdom',value:15},
        {name:'Georgia',value:15},
        {name:'Ghana',value:15},
        {name:'Guinea',value:15},
        {name:'Gambia',value:15},
        {name:'Guinea Bissau',value:15},
        {name:'Equatorial Guinea',value:15},
        {name:'Greece',value:15},
        {name:'Greenland',value:15},
        {name:'Guatemala',value:15},
        {name:'French Guiana',value:15},
        {name:'Guyana',value:15},
        {name:'Honduras',value:15},
        {name:'Croatia',value:15},
        {name:'Haiti',value:15},
        {name:'Hungary',value:15},
        {name:'Indonesia',value:15},
        {name:'India',value:15},
        {name:'Ireland',value:15},
        {name:'Iran',value:15},
        {name:'Iraq',value:15},
        {name:'Iceland',value:15},
        {name:'Israel',value:15},
        {name:'Italy',value:15},
        {name:'Jamaica',value:15},
        {name:'Jordan',value:15},
        {name:'Japan',value:15},
        {name:'Kazakhstan',value:15},
        {name:'Kenya',value:15},
        {name:'Kyrgyzstan',value:15},
        {name:'Cambodia',value:15},
        {name:'South Korea',value:15},
        {name:'Kosovo',value:15},
        {name:'Kuwait',value:15},
        {name:'Laos',value:15},
        {name:'Lebanon',value:15},
        {name:'Liberia',value:15},
        {name:'Libya',value:15},
        {name:'Sri Lanka',value:15},
        {name:'Lesotho',value:15},
        {name:'Lithuania',value:15},
        {name:'Luxembourg',value:15},
        {name:'Latvia',value:15},
        {name:'Morocco',value:15},
        {name:'Moldova',value:15},
        {name:'Madagascar',value:15},
        {name:'Mexico',value:15},
        {name:'Macedonia',value:15},
        {name:'Mali',value:15},
        {name:'Myanmar',value:15},
        {name:'Montenegro',value:15},
        {name:'Mongolia',value:15},
        {name:'Mozambique',value:15},
        {name:'Mauritania',value:15},
        {name:'Malawi',value:15},
        {name:'Malaysia',value:15},
        {name:'Namibia',value:15},
        {name:'New Caledonia',value:15},
        {name:'Niger',value:15},
        {name:'Nigeria',value:15},
        {name:'Nicaragua',value:15},
        {name:'Netherlands',value:15},
        {name:'Norway',value:15},
        {name:'Nepal',value:15},
        {name:'New Zealand',value:15},
        {name:'Oman',value:15},
        {name:'Pakistan',value:15},
        {name:'Panama',value:15},
        {name:'Peru',value:15},
        {name:'Philippines',value:15},
        {name:'Papua New Guinea',value:15},
        {name:'Poland',value:15},
        {name:'Puerto Rico',value:15},
        {name:'North Korea',value:15},
        {name:'Portugal',value:15},
        {name:'Paraguay',value:15},
        {name:'Qatar',value:15},
        {name:'Romania',value:15},
        {name:'Russia',value:15},
        {name:'Rwanda',value:15},
        {name:'Western Sahara',value:15},
        {name:'Saudi Arabia',value:15},
        {name:'Sudan',value:15},
        {name:'South Sudan',value:15},
        {name:'Senegal',value:15},
        {name:'Solomon Islands',value:15},
        {name:'Sierra Leone',value:15},
        {name:'El Salvador',value:15},
        {name:'Somaliland',value:15},
        {name:'Somalia',value:15},
        {name:'Republic of Serbia',value:15},
        {name:'Suriname',value:15},
        {name:'Slovakia',value:15},
        {name:'Slovenia',value:15},
        {name:'Sweden',value:15},
        {name:'Swaziland',value:15},
        {name:'Syria',value:15},
        {name:'Chad',value:15},
        {name:'Togo',value:15},
        {name:'Thailand',value:15},
        {name:'Tajikistan',value:15},
        {name:'Turkmenistan',value:15},
        {name:'East Timor',value:15},
        {name:'Trinidad and Tobago',value:15},
        {name:'Tunisia',value:15},
        {name:'Turkey',value:15},
        {name:'United Republic of Tanzania',value:15},
        {name:'Uganda',value:15},
        {name:'Ukraine',value:15},
        {name:'Uruguay',value:15},
        {name:'United States of America',value:15},
        {name:'Uzbekistan',value:15},
        {name:'Venezuela',value:15},
        {name:'Vietnam',value:15},
        {name:'Vanuatu',value:15},
        {name:'West Bank',value:15},
        {name:'Yemen',value:15},
        {name:'South Africa',value:15},
        {name:'Zambia',value:15},
      ],
  }
}